### ISSUE TITLE
BLEbee 2.0.0 measurements are truncated or missed at high CPM levels

### ISSUE THREAD

**Issue by nokton** [mcrollin/Drivecast#14]

**Comment by mcrollin** [comment]
Hi Pieter, could you provide a screenshot please?

**Comment by nokton** [comment]
Am collecting right now

**Comment by nokton** [comment]
![](http://i.imgur.com/aEJD06H.jpg)

**Comment by nokton** [comment]
It either truncates or drops/misses the entire row

**Comment by nokton** [comment]
Please look at time stamp to see rows got missed

**Comment by nokton** [comment]
V2.0.1 doesn't have this problem.

**Comment by mcrollin** [comment]
OK. I'll have a look at it.

**Comment by nokton** [comment]
Drops also happen at low levels, though it is less pronounced (rows are not missed, only last few characters are)

**Comment by nokton** [comment]
![](http://i.imgur.com/hq9Gq9d.jpg)

**Comment by mcrollin** [comment]
The issue comes from the BLEBee chipset.
